export const FEATURE_KEYS = {
  PARTY_CREATION: "PARTY_CREATION",
  GUEST_CREATION: "GUEST_CREATION",
  PARTY_VIEW: "PARTY_VIEW",
  REUSABLE_LAYOUTS: "REUSABLE_LAYOUTS",
  LAYOUT_EDIT: "LAYOUT_EDIT",
} as const;
